export const messages ={
    'de':{
        appTitle: 'Zahnarzt Praxis Kundakji & Partner',
        mnuKontakt: 'Kontakt',
        mnuLeistungen: 'Leistungen',
        mnuNotdienst: 'Notdienst',
        mnuOffnungsZeiten: 'Öffnungszeiten',
        mnuPraxis: 'Praxis',
        mnuStandort: 'Standort',
        praxisTeam: 'Das Team der Zahnarztpraxis',
        mnuAertzte: 'Ärtzte',
        mnuTeam:'Team',
        mnuTour:'Tour',
        actNachricht:'Nachricht',
        dct_name_sa:'Saad Kundakji',
        dct_name_aa:'Ahmad Alluh',
        dct_name_aj:'Ayman Jajeh',
        dct_pos_za:'Zahnarzt',
        titleServices:'Zahnärztliche Behandlungen',
        srv_implantologie:'Implantologie',
        srv_chirurgische: 'Chirurgische Leistungen',
        srv_funkDiag:'Funktionsdiagnostik',
        titleTour:'Rundgang durch die Klinik',

    },
    'ar':{
        appTitle: 'عيادة طبيب الأسنان د سعد قندقجى و شركائه ',
        mnuPraxis: 'العيادة',
        mnuLeistungen: 'خدمات',
        mnuKontakt: 'الاتصال',
        mnuNotdienst: 'خدمات الطوارئ',
        mnuOffnungsZeiten: 'أوقات العمل',
        mnuStandort: 'الموقع',
        praxisTeam: 'فريق عيادة طب الأسنان',
        mnuAertzte: 'الأطباء',
        mnuTeam:'فريق',
        mnuTour:'جولة',
        actNachricht:'رسالة ',
        dct_name_sa:'د سعد قندقجى',
        dct_name_aa:'أحمد اللوح',
        dct_name_aj:'أيمن جاجه',
        dct_pos_za:'دكتورالاسنان',
        titleServices:'علاجات الأسنان',
        srv_implantologie:'زراعة الأسنان',
        srv_chirurgische: 'الخدمات الجراحية',
        srv_funkDiag:'التشخيصات الوظيفية',
        titleTour: 'جولة في أرجاء العيادة ',
    },
    'en':{
        appTitle: 'Dentist clinic Kundakji & Partner',
        mnuPraxis: 'Clinic',
        mnuLeistungen: 'Services',
        mnuKontakt: 'Contact',
        mnuNotdienst: 'Emergency service',
        mnuOffnungsZeiten: 'opening hours',
        mnuStandort: 'Location',
        praxisTeam: 'The Team of the dental Clinic',
        mnuAertzte: 'Doctors',
        mnuTeam:'Team',
        mnuTour:'Tour',
        actNachricht:'Message',
        dct_name_sa:'Saad Kundakji',
        dct_name_aa:'Ahmad Alluh',
        dct_name_aj:'Ayman Jajeh',
        dct_pos_za:'Dentist',
        titleServices:'Dental treatments',
        srv_implantologie:'Implantology',
        srv_chirurgische: 'Surgical services',
        srv_funkDiag:'Functional diagnostics',
        titleTour: 'Tour around the clinic',
    },

}




export default messages;