export const messages ={
    'de':{
        appTitle: 'Zahnarzt Praxis Kundakji & Partner',
        mnuKontakt: 'Kontakt',
        mnuLeistungen: 'Leistungen',
        mnuNotdienst: 'Notdienst',
        mnuOffnungsZeiten: 'Öffnungszeiten',
        mnuPraxis: 'Praxis',
        mnuStandort: 'Standort',
        praxisDocs: 'Ärzteteam der Klinik',
        praxisTeam: 'Das Team der Zahnarztpraxis',
        mnuAertzte: 'Ärtzte',
        mnuTeam:'Team',
        mnuTour:'Tour',
        actNachricht:'Nachricht',
        dct_name_sa:'Saad Kundakji',
        dct_name_aa:'Ahmad Alluh',
        dct_name_aj:'Ayman Jajeh',
        dct_pos_za:'Zahnarzt',
        titleServices:'Zahnärztliche Behandlungen',
        srv_implantologie:'Implantologie',
        srv_chirurgische: 'Chirurgische Leistungen',
        srv_funkDiag:'Funktionsdiagnostik',
        srv_generalDiag:'Allgemeine Diagnostik',
        srv_cosmetic:'Kosmetische Leistungen',
        titleTour:'Rundgang durch die Klinik',
        team_pos_ab:'Auszubildende',
        team_pos_zf:'Zahnmedizinische Fachangestellte',
        team_name_ma1:'Mustermann Maximilian',
        day_Mon:'Montag',
        day_Tus:'Dienstag',
        day_Wed:'Mittwoch',
        day_Thu:'Donnerstag',
        day_Fri:'Freitag',
        day_Sat:'Samstag',
        day_Sun:'Sonntag',
        txt_Closed:'geschlossen',
        txt_feedback:'Rückmeldung',
        feedback_1:'Und immer ohne Angst einfach hingehen und man wird schmerzfrei behandelt.',
        feedback_2:'Das die Ärzte auf Arabisch sprechen stört mich persönlich überhaupt nicht.',
        feedback_3:'Ich war bei Herr Faress al Maghribi (Partner von Herr Kundakji) sehr guter Arzt.',
        titleOrt:'Der Standort',
        titleEmergency:'Was ist im Notfall zu tun?',
        prg_emergency:'Sollten Sie außerhalb der Sprechzeiten oder an Sonn- und Feiertagen starke Zahnschmerzen oder andere akute Beschwerden bekommen, dann entnehmen Sie die Nummer der diensthabenden Kollegen/innen aus folgende Link unten',
        frm_name:'Name',
        frm_mail:'E-Mail',
        frm_text:'Text',
        frm_send:'Senden',
        txtBooking:'Online Termin',
        stp_type:'Behandlung',
        txt_apt_treatType:'Bitte wählen Sie eine Behandlung!',
        apt_trt_control:'Kontrolle & Beratung',
        apt_trt_cleaning:'Zahnreinigung',
        apt_trt_invisalign:'Invisalign',
        apt_trt_pain:'Schmerzbehandlung',
        apt_trt_whitening:'Bleaching',
        txt_apt_treatPatient:'Sind Sie bereits Patient bei uns?',
        stp_patient:'Der Patient',
        apt_pnt_exists:'Ja',
        apt_pnt_not_exist:'Nein',
        stp_staff:'Der Zahnarzt',
        txt_apt_treatHandler:'Bitte wählen Sie einen Behandler!',
        txt_quick_apt:'Frühester Termin',
        stp_insurance:'Versicherung',
        txt_apt_insurance:'Wie sind Sie versichert?',
        apt_ins_prv:'Privat versichert',
        apt_ins_gov:'Gesetzlich versichert',
        apt_ins_tooth:'Zahnzusatzversicherung',
        stp_date:'Termin',
        txt_apt_treatDate:'Bitte wählen Sie einen Termin!',
        stp_confirm:'Bestätigung',
        txt_apt_confirm:'Die Termin Bestätigung',
        month_1:'Januar',
        month_2:'Februar',
        month_3:'März',
        month_4:'April',
        month_5:'Mai',
        month_6:'Juni',
        month_7:'Juli',
        month_8:'August',
        month_9:'September',
        month_10:'Oktober',
        month_11:'November',
        month_12:'November',
        gender_male:'Herr',
        gender_female:'Frau',
        lbl_name:'Vorname',
        lbl_family_name:'Nachname',
        frm_tel:'Telefonnummer',
        frm_val_email_req:'E-Mail ist erforderlich',
        frm_book:'Termin buchen',

    },
    'ar':{
        appTitle: 'عيادة طبيب الأسنان د سعد قندقجى و شركائه ',
        mnuPraxis: 'العيادة',
        mnuLeistungen: 'خدمات',
        mnuKontakt: 'الاتصال',
        mnuNotdienst: 'خدمات الطوارئ',
        mnuOffnungsZeiten: 'أوقات العمل',
        mnuStandort: 'الموقع',
        praxisDocs: 'فريق أطباء العيادة',
        praxisTeam: 'فريق عيادة طب الأسنان',
        mnuAertzte: 'الأطباء',
        mnuTeam:'فريق',
        mnuTour:'جولة',
        actNachricht:'رسالة ',
        dct_name_sa:'د سعد قندقجى',
        dct_name_aa:'أحمد اللوح',
        dct_name_aj:'أيمن جاجه',
        dct_pos_za:'دكتورالاسنان',
        titleServices:'علاجات الأسنان',
        srv_implantologie:'زراعة الأسنان',
        srv_chirurgische: 'الخدمات الجراحية',
        srv_funkDiag:'التشخيصات الوظيفية',
        srv_generalDiag:'التشخيصات العامة',
        srv_cosmetic:'خدمات التجميل',
        titleTour: 'جولة في أرجاء العيادة ',
        team_pos_ab:'المتدرب',
        team_pos_zf:'مساعد طبيب الاسنان',
        team_name_ma1:'نموذج أسم',
        day_Mon:'الاثنين',
        day_Tus:'الثلاثاء',
        day_Wed:'الأربعاء',
        day_Thu:'الخميس',
        day_Fri:'الجمعة ',
        day_Sat:'السبت',
        day_Sun:'الأحد',
        txt_Closed:'مغلق',
        txt_feedback:'تعليقات',
        feedback_1:'دائمًا اذهب إلى هناك دون خوف وستتم معاملتك بدون ألم',
        feedback_2:'أن يتحدث الأطباء باللغة العربية لا يزعجني شخصيًا على الإطلاق.',
        feedback_3:'كان طبيبا جيدا جدا السيد فارس المغربي (شريك السيد قندقجى)',
        titleOrt:'الموقع',
        titleEmergency:'ماذا تفعل في حالة الطوارئ؟',
        prg_emergency:'إذا كنت تعاني من ألم شديد في الأسنان أو شكاوى حادة أخرى خارج ساعات العمل أو أيام الأحد والعطلات الرسمية ، فيمكنك العثور على عدد الزملاء المناوبين في الرابط أدناه ',
        frm_name:'الأسم',
        frm_mail:'البريد الإلكتروني',
        frm_text:'الرسالة ',
        frm_send:'أرسل ',
        txtBooking:'حجز موعد',
        stp_type:'نوع العلاج',
        txt_apt_treatType:'الرجاء اختيار العلاج!',
        apt_trt_control:'الفحص والمشورة',
        apt_trt_cleaning:'تنظيف الأسنان',
        apt_trt_invisalign:'تقويم الأسنان',
        apt_trt_pain:'معالجة الألم',
        apt_trt_whitening:'التبييض',
        txt_apt_treatPatient: 'هل أنت مريض العيادة؟',
        stp_patient:'المريض',
        apt_pnt_exists:'نعم',
        apt_pnt_not_exist:'كلا',
        stp_staff:'طبيب الاسنان',
        txt_apt_treatHandler:'الرجاء اختيار طبيبك المفضل!',
        txt_quick_apt:'أقرب موعد',
        stp_insurance:'التأمين الصحي',
        txt_apt_insurance:'ما هي صيغة التأمين الصحي لديك؟',
        apt_ins_prv:'مؤمن على القطاع الخاص',
        apt_ins_gov:'تأمين حكومي',
        apt_ins_tooth:'تأمين خاص على الأسنان',
        stp_date:'ألموعد',
        txt_apt_treatDate:'الرجاء اختيار ألموعد المناسب !',
        stp_confirm:'الحجز',
        txt_apt_confirm:'تأكيد الحجز',
        month_1:'كانون الثاني - يناير',
        month_2:'شباط - فبراير',
        month_3:'ذار - مارس',
        month_4:'نيسان - ابريل ',
        month_5:'يار - مايو',
        month_6:'حزيران - يونيو',
        month_7:'تموز - يوليو ',
        month_8:'آب - أغسطس',
        month_9:'أيلول - سبتمبر',
        month_10:'تشرين الأول - أكتوبر',
        month_11:'تشرين الثاني - نوفمبر',
        month_12:'كانون الأول - ديسمبر',
        gender_male:'ذكر',
        gender_female:'أنثى',
        lbl_name:'الاسم الأول',
        lbl_family_name:'إسم العائلة',
        frm_tel:'رقم ألهاتف',
        frm_val_email_req:'البريد الالكتروني مطلوب',
        frm_book:'أحجز الموعد ',


    },
    'en':{
        appTitle: 'Dentist clinic Kundakji & Partner',
        mnuPraxis: 'Clinic',
        mnuLeistungen: 'Services',
        mnuKontakt: 'Contact',
        mnuNotdienst: 'Emergency service',
        mnuOffnungsZeiten: 'opening hours',
        mnuStandort: 'Location',
        praxisDocs: 'Medical team of the clinic',
        praxisTeam: 'The Team of the dental Clinic',
        mnuAertzte: 'Doctors',
        mnuTeam:'Team',
        mnuTour:'Tour',
        actNachricht:'Message',
        dct_name_sa:'Saad Kundakji',
        dct_name_aa:'Ahmad Alluh',
        dct_name_aj:'Ayman Jajeh',
        dct_pos_za:'Dentist',
        titleServices:'Dental treatments',
        srv_implantologie:'Implantology',
        srv_chirurgische: 'Surgical services',
        srv_funkDiag:'Functional diagnostics',
        srv_generalDiag:'General diagnostics',
        srv_cosmetic:'Cosmetic services',
        titleTour: 'Tour around the clinic',
        team_pos_ab:'trainee',
        team_pos_zf:'Dental assistant',
        team_name_ma1:'Sample Maximilian',
        day_Mon:'Monday',
        day_Tus:'Tuesday',
        day_Wed:'Wednesday',
        day_Thu:'Thursday',
        day_Fri:'Friday',
        day_Sat:'Saturday',
        day_Sun:'Sunday',
        txt_Closed:'closed',
        txt_feedback:'Feedback',
        feedback_1:'And always just go there without fear and you will be treated painlessly.',
        feedback_2:'That the doctors speak in Arabic doesn\'t bother me personally at all.',
        feedback_3:'Mr. Faress al Maghribi (partner of Mr. Kundakji) was a very good doctor ',
        titleOrt:'The Location',
        titleEmergency:'What to do in an emergency?',
        prg_emergency:'If you get severe toothache or other acute complaints outside of office hours or on Sundays and public holidays, you can find the number of the colleagues on duty from the link below',
        frm_name:'Name',
        frm_mail:'E-Mail',
        frm_text:'Text',
        frm_send:'Send',
        txtBooking:'Online appointment',
        stp_type:'Treatment',
        txt_apt_treatType:'Please choose a treatment!',
        apt_trt_control:'Control & advice',
        apt_trt_cleaning:'Teeth cleaning',
        apt_trt_invisalign:'Invisalign',
        apt_trt_pain:'Pain treatment',
        apt_trt_whitening:'Whitening',
        txt_apt_treatPatient: 'Are you already our patient?',
        stp_patient:'The Patient',
        apt_pnt_exists:'Yes',
        apt_pnt_not_exist:'No',
        stp_staff:'The Dentist',
        txt_apt_treatHandler:'Please choose your Doctor!',
        txt_quick_apt:'Earliest appointment',
        stp_insurance:'Insurance',
        txt_apt_insurance:'How are you insured?',
        apt_ins_prv:'Privately insured',
        apt_ins_gov:'Statutory insurance',
        apt_ins_tooth:'Dental insurance',
        stp_date:'Appointment',
        txt_apt_treatDate:'Please choose an appointment!',
        stp_confirm:'Confirmation',
        txt_apt_confirm:'The Date confirmation',
        month_1:'January',
        month_2:'February',
        month_3:'February',
        month_4:'April',
        month_5:'May',
        month_6:'June',
        month_7:'July',
        month_8:'August',
        month_9:'September',
        month_10:'October',
        month_11:'November',
        month_12:'December',
        gender_male:'Male',
        gender_female:'Female',        
        lbl_name:'Forename',
        lbl_family_name:'Surname',
        frm_tel:'Telephone Number',
        frm_val_email_req:'Email is required',
        frm_book:'Book an appointment',
    },

}




export default messages;